fire:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux
  fields:
    data:
      required: false
      example: '{"room": "kitchen"}'
      selector:
        object:

dismiss:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux

ack:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux

unack:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux

snooze:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux
  fields:
    duration:
      required: true
      example: "00:30:00"
      selector:
        duration:

disable:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux

enable:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux

suspend:
  target:
    entity:
      integration: alert_redux
      domain: alert_redux
  fields:
    duration:
      required: false
      example: "02:00:00"
      selector:
        duration:
    until:
      required: false
      example: "2026-10-01 08:00:00"
      selector:
        datetime:
